name: Update Changelog

on:
  push:
    branches:
      - main

jobs:
  update-changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

      - name: Install git-chglog
        run: |
          curl -L https://github.com/git-chglog/git-chglog/releases/download/0.15.0/git-chglog-linux-amd64 --progress-bar --location --remote-name --silent
          chmod +x git-chglog-linux-amd64
          sudo mv git-chglog-linux-amd64 /usr/local/bin/git-chglog

      - name: Update Changelog (main)
        run: |
          git fetch
          git checkout -b chore/update-changelog-main
          git-chglog --output CHANGELOG.md
          git add CHANGELOG.md
          git commit -m "chore: Update CHANGELOG.md" || true
          git push --set-upstream origin chore/update-changelog-main || true

      - name: Create Pull Request (main)
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore: Update CHANGELOG.md"
          title: "chore: Update CHANGELOG.md"
          branch: chore/update-changelog-main
          base: main

      - name: Update Changelog (develop)
        run: |
          git fetch
          git checkout develop
          git checkout -b chore/update-changelog-develop
          git-chglog --output CHANGELOG.md
          git add CHANGELOG.md
          git commit -m "chore: Update CHANGELOG.md" || true
          git push --set-upstream origin chore/update-changelog-develop || true

      - name: Create Pull Request (develop)
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore: Update CHANGELOG.md"
          title: "chore: Update CHANGELOG.md"
          branch: chore/update-changelog-develop
          base: develop
